-- ============================================================
-- Kalam Spark — Supabase PostgreSQL Schema  v1.0
-- Run this entire script once in the Supabase SQL Editor to
-- initialise all tables required by the application.
-- ============================================================

-- ------------------------------------------------------------
-- 1. Users
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
  id                   TEXT PRIMARY KEY,
  name                 TEXT,
  email                TEXT,
  avatar               TEXT,
  branch               TEXT,
  year                 TEXT,
  education_level      TEXT,
  school_board         TEXT,
  grade_or_semester    TEXT,
  college_name         TEXT,
  study_hours_per_day  INT,
  target_year          TEXT,
  city                 TEXT,
  motivation           TEXT,
  dream                TEXT,
  current_stage_index  INT DEFAULT 0,
  onboarding_complete  BOOLEAN DEFAULT FALSE,
  xp                   INT DEFAULT 0,
  streak               INT DEFAULT 0,
  rewards              JSONB DEFAULT '[]'::jsonb,
  settings             JSONB,
  file_speaker_data    JSONB,
  podcasts             JSONB DEFAULT '[]'::jsonb,
  last_sync            TIMESTAMPTZ,
  created_at           TIMESTAMPTZ DEFAULT NOW()
);

-- ------------------------------------------------------------
-- 2. Roadmaps  (AI-generated; cached per user)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS roadmaps (
  user_id      TEXT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  roadmap_data JSONB,
  updated_at   TIMESTAMPTZ DEFAULT NOW()
);

-- ------------------------------------------------------------
-- 3. Tasks  (Daily planner tasks)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS tasks (
  id             TEXT PRIMARY KEY,
  user_id        TEXT REFERENCES users(id) ON DELETE CASCADE,
  title          TEXT NOT NULL,
  type           TEXT,
  linked_subject TEXT,
  completed      BOOLEAN DEFAULT FALSE,
  date           TIMESTAMPTZ,
  updated_at     TIMESTAMPTZ DEFAULT NOW(),
  created_at     TIMESTAMPTZ DEFAULT NOW()
);

-- ------------------------------------------------------------
-- 4. Completed Stages
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS completed_stages (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id      TEXT REFERENCES users(id) ON DELETE CASCADE,
  stage_id     TEXT NOT NULL,
  completed_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (user_id, stage_id)
);

-- ------------------------------------------------------------
-- 5. Mentor Messages  (AI chat history per session)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS mentor_messages (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    TEXT REFERENCES users(id) ON DELETE CASCADE,
  session_id TEXT NOT NULL DEFAULT 'legacy',
  role       TEXT NOT NULL CHECK (role IN ('user', 'ai')),
  text       TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ------------------------------------------------------------
-- 6. Flashcards  (Spaced-repetition cards)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS flashcards (
  id         TEXT PRIMARY KEY,
  user_id    TEXT REFERENCES users(id) ON DELETE CASCADE,
  deck_id    TEXT NOT NULL,
  front      TEXT NOT NULL,
  back       TEXT NOT NULL,
  active     BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ------------------------------------------------------------
-- 7. Flashcard Stats  (FSRS + Ebisu scheduling per card)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS flashcard_stats (
  id                 TEXT PRIMARY KEY,
  user_id            TEXT REFERENCES users(id) ON DELETE CASCADE,
  flashcard_id       TEXT REFERENCES flashcards(id) ON DELETE CASCADE,
  stability          FLOAT   DEFAULT 1.0,
  difficulty         FLOAT   DEFAULT 5.0,
  repetition_count   INT     DEFAULT 0,
  ebisu_model        JSONB   DEFAULT '[1.0, 1.0, 0.0]'::jsonb,
  next_review        TIMESTAMPTZ DEFAULT NOW(),
  last_review        TIMESTAMPTZ,
  last_grade         INT,
  review_count       INT     DEFAULT 0,
  created_at         TIMESTAMPTZ DEFAULT NOW(),
  updated_at         TIMESTAMPTZ DEFAULT NOW()
);

-- ------------------------------------------------------------
-- 8. Task Revisions  (FSRS scheduling for completed tasks)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS task_revisions (
  id                 TEXT PRIMARY KEY,
  user_id            TEXT REFERENCES users(id) ON DELETE CASCADE,
  task_id            TEXT NOT NULL,
  task_title         TEXT NOT NULL,
  task_type          TEXT DEFAULT 'theory',
  stability          FLOAT   DEFAULT 1.0,
  difficulty         FLOAT   DEFAULT 5.0,
  repetition_count   INT     DEFAULT 0,
  next_review        TIMESTAMPTZ DEFAULT NOW(),
  last_review        TIMESTAMPTZ,
  last_quiz_score    INT,
  total_reviews      INT     DEFAULT 0,
  created_at         TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (user_id, task_id)
);

-- ============================================================
-- Row Level Security
-- ============================================================
ALTER TABLE users             ENABLE ROW LEVEL SECURITY;
ALTER TABLE roadmaps          ENABLE ROW LEVEL SECURITY;
ALTER TABLE tasks             ENABLE ROW LEVEL SECURITY;
ALTER TABLE completed_stages  ENABLE ROW LEVEL SECURITY;
ALTER TABLE mentor_messages   ENABLE ROW LEVEL SECURITY;
ALTER TABLE flashcards        ENABLE ROW LEVEL SECURITY;
ALTER TABLE flashcard_stats   ENABLE ROW LEVEL SECURITY;
ALTER TABLE task_revisions    ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public access to users"            ON users            FOR ALL USING (true);
CREATE POLICY "Allow public access to roadmaps"         ON roadmaps         FOR ALL USING (true);
CREATE POLICY "Allow public access to tasks"            ON tasks            FOR ALL USING (true);
CREATE POLICY "Allow public access to completed_stages" ON completed_stages FOR ALL USING (true);
CREATE POLICY "Allow public access to mentor_messages"  ON mentor_messages  FOR ALL USING (true);
CREATE POLICY "Allow public access to flashcards"       ON flashcards       FOR ALL USING (true);
CREATE POLICY "Allow public access to flashcard_stats"  ON flashcard_stats  FOR ALL USING (true);
CREATE POLICY "Allow public access to task_revisions"   ON task_revisions   FOR ALL USING (true);

-- ============================================================
-- Indexes
-- ============================================================
CREATE INDEX IF NOT EXISTS idx_flashcards_user_deck
  ON flashcards (user_id, deck_id);

CREATE INDEX IF NOT EXISTS idx_flashcard_stats_user_next_review
  ON flashcard_stats (user_id, next_review);

CREATE INDEX IF NOT EXISTS idx_flashcard_stats_flashcard
  ON flashcard_stats (flashcard_id);

CREATE INDEX IF NOT EXISTS idx_task_revisions_user_next_review
  ON task_revisions (user_id, next_review);

-- ============================================================
-- Triggers for auto-updating updated_at timestamp
-- ============================================================
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
   NEW.updated_at = NOW();
   RETURN NEW;
END;
$$ language 'plpgsql';

CREATE OR REPLACE TRIGGER update_roadmaps_updated_at BEFORE UPDATE ON roadmaps FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE OR REPLACE TRIGGER update_tasks_updated_at BEFORE UPDATE ON tasks FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE OR REPLACE TRIGGER update_flashcards_updated_at BEFORE UPDATE ON flashcards FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE OR REPLACE TRIGGER update_flashcard_stats_updated_at BEFORE UPDATE ON flashcard_stats FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
